version: "3"
services:
  php:
    build:
      context: .
      dockerfile: php74.dockerfile
    env_file:
      - configs/vars.env
    volumes:
      - .:/var/www
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: ["php", "test.php"]
    stdin_open: true
    tty: true